resource_group_name = "test-azure-iac-dev-rg"
storage_account_name = "testazureiacdevstoracc"
storage_container_name = "test-azure-iac-dev-container"
function_app_name = "test-azure-iac-dev-func"
service_plan_name = "test-azure-iac-dev-srvplan"
service_plan_sku = "B1"